version = 0.1

# Configuraci贸n por defecto (default)
[default]
[default.global.parameters]
stack_name = "sam-base"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "sam-base"
region = "us-east-1"
parameter_overrides = "stage=\"LOCAL\" tableName=\"localTable\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"


##########################################
###  Configuraci贸n para el stage 'dev' ###
##########################################
[dev]
[dev.deploy.parameters]
stack_name = "sam-base-dev"
resolve_s3 = true
s3_prefix = "sam-base-bucket-DEV"
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
parameter_overrides = "stage=\"DEV\" tableName=\"devTable\""


##########################################
### Configuraci贸n para el stage 'QA' ####
##########################################
[qa]
[QA.deploy.parameters]
stack_name = "sam-base-QA"
resolve_s3 = true
s3_prefix = "sam-base-bucket-QA"
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
parameter_overrides = "stage=\"QA\" tableName=\"QATable\""


##########################################
### Configuraci贸n para el stage 'prod' ###
##########################################
[prod]
[prod.deploy.parameters]
stack_name = "sam-base-prod"
resolve_s3 = true
s3_prefix = "sam-base-bucket-PROD"
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
parameter_overrides = "stage=\"PROD\" tableName=\"prodTable\""