name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install pip
        run: sudo apt-get install -y python3-pip

      - name: Set up AWS SAM CLI
        run: pip3 install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install esbuild globally
        run: npm install -g esbuild

      - name: Verify esbuild installation
        run: esbuild --version

      - name: Build with SAM inside Docker
        run: docker run --rm -v $(pwd):/app -w /app node:20 bash -c "apt-get update && apt-get install -y python3-pip && pip3 install aws-sam-cli && npm install -g esbuild && npm ci && sam build --use-container"

      - name: Deploy with SAM
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
