name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  sam-validate-build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies with Apt Get
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 jq -y
      - name: Install Pip Dependencies for CI
        run: |
          pip3 install pytest
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
      - name: SAM Validate
        run: |
          sam validate

      - name: SAM Build
        run: |
          sam build

      - name: SAM Deploy
        run: |
          # Create S3 Bucket to store code
          sam deploy --no-confirm-changeset