name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci  # O npm install si no tienes package-lock.json

      - name: Install esbuild globally
        run: npm install -g esbuild

  test:
    runs-on: ubuntu-latest
    needs: install  # Dependencia de la etapa de instalación
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test  # Aquí se asume que usas jest o alguna otra herramienta de testing

  build:
    runs-on: ubuntu-latest
    needs: test  # Dependencia de la etapa de test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build with SAM
        run: sam build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Dependencia de la etapa de build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with SAM
        run: sam deploy --config-env dev --no-confirm-changeset --no-fail-on-empty-changeset
